Help debugging kgetattr when an attr is missing
If AttributeError is being raised there, obj is _AttrUnset. There's no reason
in saying that "_AttrUnset has no attribute 'foo'". This makes it report the
correct model name.

Change-Id: If828f30cc3fc8fb4223e662e162c10bc2066419a